### ISSUE TITLE
Wirement Integration in Navigation.html

### ISSUE THREAD

**Issue by proballstar** [firebolt-space/atlas#3]
**Wirement Integration in Navigation.html**
With Wirement Integration it  and the angular components, some Wirement Functionality is not being allowed b/c 
**To Reproduce**
1. Go to 'navigation.html'
2. Change the code to Wirement navbar
3. Run Sever.py

**Expected behavior**
It should show a navigation bar with built-in splash functionality

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: "don't know"

**Comment by proballstar** [comment]
Also it u look it is about 

1. <mdb-navbar
2.  mdbRippleRadius
3. mat-raised-button color
and .scss extension of styling

**Comment by aaronhma** [comment]
@proballstar I think that initially, SCSS was the style of choice, but was then changed to CSS. But Wiremint wasn't changed to preserve its awesome theme and beautiful web page.

**Comment by proballstar** [comment]
@aaronhma Right now its more of SCSS problem but also because of the mdb-navbar element that really caused the err because it controlled the mdbRippleRadius which made it not have that splashy feeling that would have been there. The Mat-Raised-Button Color just seems like changing the color of the theme of the buttons to a different one. I think you could solve it by just integrating SCSS to CSS but then you would have to be able to integrate the mdb and mat-rasised-button color which I think were components that you added in the other webpages with the .ts files so I we may be able to my converting the file types and finding the code. Respond Soon, Proballstar

**Comment by aaronhma** [comment]
@proballstar <mat-raised-button> creates a new problem in Honeycomb.

**Comment by proballstar** [comment]
@aaronhma  this honeycomb problem is before the other issue
@aaronhma  also the other problem will be dealt with by me so just fix **_The Wirement Intergration Problem_**

**Comment by proballstar** [comment]
@aaronhma do u known how to solve it

**Comment by aaronhma** [comment]
@proballstar What exactly do you mean by "error"?

**Comment by proballstar** [comment]
It does not allow it because of certain parts you used as part of .scss and angular. So the navbar won't in the same way as the Wirement navbar. I need to fix integration so I will be able to add more Wirement functionality. I am working on the flutter apps.

**Comment by aaronhma** [comment]
@proballstar Ok, let me close this issue, as I will work on it.
@github Bot, move this to TODO in Atlas automation, please.
