### ISSUE TITLE
Make the Rocket Simulator to allow a Windows Machine to run the simulatr

### ISSUE THREAD

**Issue by proballstar** [firebolt-space/atlas#4]
Not Allowing The Simulator to run on Google Chrome on windows

**Comment by aaronhma** [comment]
@proballstar I'd consider this an "extremely low" priority for Atlas. For that, I'm closing this issue.

**Comment by proballstar** [comment]
Then I can't see these features and that is not fair as you can see them with your Linux Ubuntu and I cannot so you should at least try

**Comment by aaronhma** [comment]
@proballstar I'll add this on TODOS, but expect this feature to be done around May.

**Comment by aaronhma** [comment]
@proballstar Actually, an update to this: We will probably never support Windows, as Windows is too slow to run the computation-hogging simulator. Windows might crash if running the simulator, so for that, I'm closing this.

**Comment by proballstar** [comment]
We have to find a way, Aaron even though computation takes time. How am I going to be able to do this how so I CANNOT run it so for that I am Reopening this because I want to be able to see this. And I CANNOT.

**Comment by aaronhma** [comment]
@proballstar The reason I'm closing this commit is that the simulator is computationally expensive. If you run it on Windows or Mac, your computer will probably crash due to the influx of binary into your computer's RAM and CPU. For that, I'm closing this issue.

**Comment by proballstar** [comment]
then how can I view it. **TELL ME** @aaronhma

**Comment by aaronhma** [comment]
@proballstar Then don't tell me that your computer crashed.
